// flow-typed signature: 5fd954f94a7af313f350af8ac7ab50b9
// flow-typed version: <<STUB>>/keypress_v^0.2.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'keypress'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "keypress" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "keypress/test" {
  declare module.exports: any;
}

// Filename aliases
declare module "keypress/index" {
  declare module.exports: $Exports<"keypress">;
}
declare module "keypress/index.js" {
  declare module.exports: $Exports<"keypress">;
}
declare module "keypress/test.js" {
  declare module.exports: $Exports<"keypress/test">;
}
