// flow-typed signature: a55f9d5971ea8d9d78c89d5fc4250abf
// flow-typed version: <<STUB>>/@versett/versett-devtools_v^1.9.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@versett/versett-devtools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@versett/versett-devtools" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@versett/versett-devtools/bin/commands/install" {
  declare module.exports: any;
}

declare module "@versett/versett-devtools/bin/commands/precommit" {
  declare module.exports: any;
}

declare module "@versett/versett-devtools/bin/commands/preparecommitmsg" {
  declare module.exports: any;
}

declare module "@versett/versett-devtools/bin/commands/release" {
  declare module.exports: any;
}

declare module "@versett/versett-devtools/bin/index" {
  declare module.exports: any;
}

// Filename aliases
declare module "@versett/versett-devtools/bin/commands/install.js" {
  declare module.exports: $Exports<
    "@versett/versett-devtools/bin/commands/install"
  >;
}
declare module "@versett/versett-devtools/bin/commands/precommit.js" {
  declare module.exports: $Exports<
    "@versett/versett-devtools/bin/commands/precommit"
  >;
}
declare module "@versett/versett-devtools/bin/commands/preparecommitmsg.js" {
  declare module.exports: $Exports<
    "@versett/versett-devtools/bin/commands/preparecommitmsg"
  >;
}
declare module "@versett/versett-devtools/bin/commands/release.js" {
  declare module.exports: $Exports<
    "@versett/versett-devtools/bin/commands/release"
  >;
}
declare module "@versett/versett-devtools/bin/index.js" {
  declare module.exports: $Exports<"@versett/versett-devtools/bin/index">;
}
declare module "@versett/versett-devtools/index" {
  declare module.exports: $Exports<"@versett/versett-devtools">;
}
declare module "@versett/versett-devtools/index.js" {
  declare module.exports: $Exports<"@versett/versett-devtools">;
}
