// @flow

module.exports = {
  CHANCE_OF_4: 0.1,
  HEURISTIC_MAX_DEPTH: 0,
  HEURISTIC_FACTOR_LOST_PENALTY: 200000,
  HEURISTIC_FACTOR_MONOTONICITY_POWER: 4,
  HEURISTIC_FACTOR_MONOTONICITY_WEIGHT: 47,
  HEURISTIC_FACTOR_MONOTONICITY_REDUCTION_IF_AT_RISK: 0.1,
  HEURISTIC_FACTOR_SUM_POWER: 4,
  HEURISTIC_FACTOR_SUM_WEIGHT: 11,
  // HEURISTIC_FACTOR_MERGES_WEIGHT: 700,
  HEURISTIC_FACTOR_EMPTY_WEIGHT: 270
};
